version: 0.2

phases:
  install:
    commands:
      - npm install --silent --no-progress npm -g
      - npm install --silent --no-progress serverless -g
  pre_build:
    commands:
      - npm install --no-progress --silent
  post_build:
    commands:
      - serverless deploy
