version: 0.2

phases:
  install:
    commands:
      - cd order && npm install --no-progress --slient
      - cd ../
      - cd product && npm install --no-progress --slient
      - cd ../
  post_build:
    commands:
      - cd order && npm run deploy
      - cd ../
      - cd product && npm run deploy
      - cd ../
